"""Template plugin generated by CyberClaw."""

from typing import Any
from cyberclaw.plugins.sdk import Plugin, PluginManifest, PluginCapability


class MyCustomPlugin(Plugin):
    """Custom extension plugin for CyberClaw."""

    manifest = PluginManifest(
        name="my_ext",
        version="0.1.0",
        description="Auto-generated template plugin",
        author="Cyber Prince Developer",
        capabilities=[PluginCapability.TOOL, PluginCapability.CHANNEL],
    )

    async def on_load(self) -> None:
        """Executed when the plugin is registered."""
        print(f"[Plugin my_ext] load completed successfully!")

    async def on_unload(self) -> None:
        """Executed during cleanup."""
        print(f"[Plugin my_ext] unload completed.")

    def get_tools(self) -> list[dict[str, Any]]:
        """Add custom tools here."""
        return [
            {
                "name": "my_ext_ping",
                "description": "Example plugin tool that returns pong",
                "parameters": {"type": "object", "properties": {}},
            }
        ]

    async def my_ext_ping(self) -> str:
        return "pong"

